<?php

return array(
	'{{ns:0}}' => '',
  '{{ns:1}}' => 'Discussione',
	'{{ns:2}}' => 'Utente',
	'{{ns:3}}' => 'Discussioni_utente',
  '{{ns:4}}' => 'Wikipedia',
	'{{ns:5}}' => 'Discussioni_Wikipedia',
	'{{ns:6}}' => ':File',
  '{{ns:7}}' => 'Discussioni_file',
	'{{ns:8}}' => 'MediaWiki',
	'{{ns:9}}' => 'Discussioni_MediaWiki',
  '{{ns:10}}' => 'Template',
	'{{ns:11}}' => 'Discussioni_template',
	'{{ns:12}}' => 'Aiuto',
  '{{ns:13}}' => 'Discussioni_aiuto',
  '{{ns:14}}' => ':Categoria',
  '{{ns:15}}' => 'Discussioni_categoria',
  '{{ns:100}}' => 'Portale',
  '{{ns:101}}' => 'Discussioni_portale',
  '{{ns:102}}' => 'Progetto',
  '{{ns:103}}' => 'Discussioni_progetto',
  '{{ns:828}}' => 'Modulo',
  '{{ns:829}}' => 'Discussioni_modulo',
);
